#!/bin/bash

#./pixelHitsAOD_cfg_split_pileup_200_10_merge_TFileService.sh
./pixelHitsAOD_cfg_split_pileup_200_3_merge_TFileService.sh
#./pixelHitsAOD_cfg_split_pileup_200_30_merge_TFileService.sh

#./pixelHitsAOD_cfg_split_pileup_300_10_merge_TFileService.sh
./pixelHitsAOD_cfg_split_pileup_300_3_merge_TFileService.sh
#./pixelHitsAOD_cfg_split_pileup_300_30_merge_TFileService.sh

#./pixelHitsAOD_cfg_split_pileup_400_10_merge_TFileService.sh
./pixelHitsAOD_cfg_split_pileup_400_3_merge_TFileService.sh
#./pixelHitsAOD_cfg_split_pileup_400_30_merge_TFileService.sh

#./pixelHitsAOD_cfg_split_pileup_500_10_merge_TFileService.sh
./pixelHitsAOD_cfg_split_pileup_500_3_merge_TFileService.sh
#./pixelHitsAOD_cfg_split_pileup_500_30_merge_TFileService.sh

wait

#./pixelHitsAOD_cfg_split_pileup_200_10_cleanup.sh
./pixelHitsAOD_cfg_split_pileup_200_3_cleanup.sh
#./pixelHitsAOD_cfg_split_pileup_200_30_cleanup.sh

#./pixelHitsAOD_cfg_split_pileup_300_10_cleanup.sh
./pixelHitsAOD_cfg_split_pileup_300_3_cleanup.sh
#./pixelHitsAOD_cfg_split_pileup_300_30_cleanup.sh

#./pixelHitsAOD_cfg_split_pileup_400_10_cleanup.sh
./pixelHitsAOD_cfg_split_pileup_400_3_cleanup.sh
#./pixelHitsAOD_cfg_split_pileup_400_30_cleanup.sh

#./pixelHitsAOD_cfg_split_pileup_500_10_cleanup.sh
./pixelHitsAOD_cfg_split_pileup_500_3_cleanup.sh
#./pixelHitsAOD_cfg_split_pileup_500_30_cleanup.sh





